### ISSUE TITLE
[Bug] Navigation Hero Tag

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#120]
Got this error when navigating from one route to another

```
Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.

Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
In this case, multiple heroes had the following tag: Default Hero tag for Cupertino navigation bars with navigator NavigatorState#038dd(tickers: tracking 4 tickers)
Here is the subtree for one of the offending heroes: Hero
    tag: Default Hero tag for Cupertino navigation bars with navigator NavigatorState#038dd(tickers: tracking 4 tickers)
    state: _HeroState#77bee
When the exception was thrown, this was the stack
#0      Hero._allHeroesFor.inviteHero.<anonymous closure>
package:flutter/…/widgets/heroes.dart:268
#1      Hero._allHeroesFor.inviteHero
package:flutter/…/widgets/heroes.dart:279
#2      Hero._allHeroesFor.visitor
package:flutter/…/widgets/heroes
```
Reference links:
-  https://stackoverflow.com/questions/54802114/reusing-widget-with-cupertino-navigation-bar-inside
- https://stackoverflow.com/questions/57595560/flutter-handling-multiple-navigation-screen-in-cupertinotabscaffold
- https://api.flutter.dev/flutter/cupertino/CupertinoNavigationBar/heroTag.html

**Comment by hashirshoaeb** [comment]
Seems like, nesting tab scaffold and page scaffold, is creating this problem.

**Comment by cyber-venom003** [comment]
@hashirshoaeb Lemme check this.

**Comment by cyber-venom003** [comment]
@hashirshoaeb I checked and found that in home_page.dart, HomePage() and ProfilePage() were rendered incorrectly. 
We forgot to use CupertinoTabView, hence I guess there was the problem because Hero can't detect the correct Widget Subtree as we didn't passed the correct BuildContext using builder property of CupertinoTabView. 
PR #125 fixes this, please review.

**Comment by hashirshoaeb** [comment]
Ah alright, i'll look into this.


Thanks @cyber-venom003

**Comment by enchance** [comment]
> Seems like, nesting tab scaffold and page scaffold, is creating this problem.

Very interesting as I have a similar layout where I'm using a `TabBar` and each view in my list of views is its own `Scaffold`. This was necessary because each tab needs its own `FloatingActionButton` making each FAB unique. I did give each fab a unique `heroTag` value but I'm still getting the error.

Funny thing is that in development the error is thrown but after deploying to the Playstore I'm not registering any exceptions in Crashlytics. Could the error only be in development?
